DROP SEQUENCE IF EXISTS seq_canciones;
DROP TABLE IF EXISTS CANCIONES;

CREATE TABLE CANCIONES
(
    ID                 VARCHAR(15),
    TITULO             VARCHAR(100),
    ARTISTA            VARCHAR(100),
    ALBUM              VARCHAR(100),
    DURACION_SEGUNDOS  NUMERIC(4),
    FECHA_ESTRENO      DATE,

    CONSTRAINT "PK_CANCIONES"                  PRIMARY KEY (ID),
    CONSTRAINT "NN_CANCIONES.TITULO"           CHECK (TITULO IS NOT NULL ),
    CONSTRAINT "NN_CANCIONES.ARTISTA"          CHECK (ARTISTA IS NOT NULL ),
    CONSTRAINT "NN_CANCIONES.FECHA_ESTRENO"    CHECK (FECHA_ESTRENO IS NOT NULL ),
    CONSTRAINT "CH_CANCIONES.DURACION"         CHECK (DURACION_SEGUNDOS > 0)
);

CREATE SEQUENCE seq_canciones MINVALUE 10 MAXVALUE 999999998 START WITH 10 INCREMENT BY 1;

INSERT INTO CANCIONES(ID, TITULO, ARTISTA, ALBUM, DURACION_SEGUNDOS, FECHA_ESTRENO)
VALUES('1', 'Dakiti', 'Bad Bunny', 'El Último Tour Del Mundo', 205, '2020-10-30');

INSERT INTO CANCIONES(ID, TITULO, ARTISTA, ALBUM, DURACION_SEGUNDOS, FECHA_ESTRENO)
VALUES('2', 'Gasolina', 'Daddy Yankee', 'Barrio Fino', 192, '2004-01-01');

INSERT INTO CANCIONES(ID, TITULO, ARTISTA, ALBUM, DURACION_SEGUNDOS, FECHA_ESTRENO)
VALUES('3', 'Safaera', 'Bad Bunny', 'YHLQMDLG', 295, '2020-02-29');

INSERT INTO CANCIONES(ID, TITULO, ARTISTA, ALBUM, DURACION_SEGUNDOS, FECHA_ESTRENO)
VALUES('4', 'Provenza', 'Karol G', 'Mañana Será Bonito', 210, '2022-04-21');

INSERT INTO CANCIONES(ID, TITULO, ARTISTA, ALBUM, DURACION_SEGUNDOS, FECHA_ESTRENO)
VALUES('5', 'Despacito', 'Luis Fonsi ft. Daddy Yankee', 'Vida', 228, '2017-01-12');

COMMIT;