quarkus.package.jar.type=uber-jar
quarkus.http.port=8080

database.host=localhost
database.port=5432
database.name=upsa
database.username=${DB_USER:postgres}
database.password=${DB_PASSWORD:postgres}


quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://${database.host}:${database.port}/${database.name}
quarkus.datasource.username=${database.username}
quarkus.datasource.password=${database.password}